In [107]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split    
from sklearn.preprocessing import StandardScaler,LabelEncoder  
from sklearn.linear_model import Perceptron    #Used for simple linear classification task
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

import tensorflow as tf
from tensorflow.keras.models import Sequential # type: ignore       #Sequential lets you build a neural network layer-by-layer in keras
from tensorflow.keras.layers import Dense # type: ignore            #Dense makes the final predictions
from tensorflow.keras.layers import Conv2D # type: ignore           #Conv2D extracts features 
from tensorflow.keras.layers import Flatten # type: ignore          #Flatten reshapes them
from tensorflow.keras.layers import MaxPooling2D # type: ignore     #Maxpooling2D reduces size
from tensorflow.keras.layers import Dropout   # type: ignore        #Dropout prevents 
from tensorflow.keras.utils import to_categorical   # type: ignore  #Converts numeric class labels into one-hot encoded format for training classification models

In [108]:
df = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

In [109]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [110]:
df_test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [111]:
df.shape

(42000, 785)

In [112]:
df_test.shape

(28000, 784)

In [113]:
df.columns

Index(['label', 'pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=785)

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB

In [115]:
df.isnull().sum()

label       0
pixel0      0
pixel1      0
pixel2      0
pixel3      0
           ..
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 785, dtype: int64

Preprocessing

In [129]:
X_train = df.drop("label",axis=1).values
y_train = df["label"].values

In [116]:
X = df.drop("label", axis=1).values
y = df["label"].values

In [117]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [118]:
print(X_train.shape)
print(X_val.shape)

print(y_train.shape)
print(y_val.shape)

(33600, 784)
(8400, 784)
(33600,)
(8400,)

In [130]:
X_train = X_train.astype("float32")  / 255.0
X_test = X_test.astype("float32")  / 255.0

In [71]:
X_test.shape

(28000, 784)

In [131]:
X_train_img = X_train.reshape(-1, 28, 28)
X_test_img = X_test.values.reshape(-1, 28, 28)

In [120]:
# y_train_cat = to_categorical(y_train, 10)
# y_test_cat = to_categorical(y_test)

In [121]:
X_train_img = X_train.reshape(-1,28,28,1)
X_val_img = X_val.reshape(-1,28,28,1)

In [132]:
y_train_cat = to_categorical(y_train, 10)
y_val_cat = to_categorical(y_val, 10)

In [124]:
print(X_train_img.shape)
print(X_val_img.shape)

print(y_train_cat.shape)
print(y_val_cat.shape)

(33600, 28, 28, 1)
(8400, 28, 28, 1)
(33600, 10)
(8400, 10)

In [93]:
perceptron = Sequential([
    Flatten(input_shape=(28,28)),
    Dense(10,activation="softmax")
])

In [94]:
perceptron.compile(optimizer="sgd",loss="categorical_crossentropy",metrics=["accuracy"])

In [133]:
history_percp = perceptron.fit(X_train_img,y_val_cat,epochs=5,
batch_size = 32,validation_data=(X_test_img,y_val_cat),verbose=1)

ValueError: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 42000
'y' sizes: 8400